services:
  nsfw-ai-microservice:
    container_name: nsfw-ai-microservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - han.city.network
    restart: unless-stopped
    environment:
      - ENV=dev
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

networks:
  han.city.network:
    external: true
